package it.polito.helpenvironmentnow.Storage;

import android.content.Context;

import androidx.room.Room;

import org.json.JSONObject;

public class MyDb {
    private static final String LOCAL_DB_NAME = "DB_JSON_CACHING";
    private StoredJsonDao storedJsonDao; // used to access the database

    public MyDb(Context context) {
        LocalStore db = Room.databaseBuilder(context, LocalStore.class, LOCAL_DB_NAME).build();
        this.storedJsonDao = db.storedJsonDao();
    }

    public void storeJsonObject(JSONObject jsonObject) {
        StoredJson currentJson = new StoredJson();
        currentJson.id = 0; // 0 means that the id will be auto-generated by Sqlite
        currentJson.jsonSave = jsonObject.toString();
        storedJsonDao.insertJson(currentJson);
    }

    public void deleteJsonObject(StoredJson storedJson) {
        storedJsonDao.deleteJson(storedJson);
    }

    public StoredJson[] getAllStoredJson() {
        return storedJsonDao.getAllStoredJson();
    }
}
